### ISSUE TITLE
Aurora crashing after lauching Minecraft client on iMacs

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#302]
Aurora crashed after launching Minecraft clients on the iMacs

**Comment by CalebUAz** [comment]
### Aurora log file on leopard:

```
[2022-04-22 10:44:16.967] [ 1247 32994] [debug] BufferedReader holds 101 frames
[2022-04-22 10:44:24.144] [ 1247 32994] [debug] BufferedReader holds 74 frames
[2022-04-22 10:44:26.251] [ 1247 33129] [error] Error reading data
[2022-04-22 10:44:29.508] [ 1247 33129] [debug] Slot 0: SlotErrors: {"Checksum":57694,"Count":1,"First":13,"Recent":13,"FirstTicks":2714741523,"RecentTicks":2714741523,"FirstHint":0,"RecentHint":0}
[2022-04-22 10:44:30.710] [ 1247 33129] [debug] BufferedReader stopped because reading from the device failed
[2022-04-22 10:44:30.710] [ 1247 33129] [debug] Switching USB-connected device to CONF mode.
[2022-04-22 10:44:48.457] [ 1247 32994] [debug] stopping BufferedReader
[2022-04-22 10:44:48.892] [ 1247 32994] [debug] temperatures (deg C): 38.9 39.0 35.0 39.3
[2022-04-22 10:44:49.142] [ 1247 32994] [debug] battery: 86.0%
[2022-04-22 10:44:49.392] [ 1247 32994] [debug] Charger connected: Yes
[2022-04-22 10:44:49.393] [ 1247 32994] [info] saved 51846 frames.
[2022-04-22 10:44:49.593] [ 1247 32994] [debug] Aurora will write the dataset using the existing folder </Users/LabWorker/data/cat/LangLab/Study3/Pilot/Exp_2022_04_22_09/leopard/fnirs/2022-04-22/2022-04-22_001>
[2022-04-22 10:44:49.599] [ 1247 32994] [debug] Writing frame_times file to /Users/LabWorker/data/cat/LangLab/Study3/Pilot/Exp_2022_04_22_09/leopard/fnirs/2022-04-22/2022-04-22_001/frame_times.npy
[2022-04-22 10:44:49.793] [ 1247 32994] [debug] pipeline ran for 5121.45s and processed 50311 chunks. crank time was: min=0.10ms, mean=0.78ms, max=434.30ms
[2022-04-22 10:44:49.813] [ 1247 29067] [debug] changing device state from State.BUSY to State.ABSENT
[2022-04-22 10:45:02.063] [ 1247 29067] [warning] N.B.: Traceback (most recent call last):
  File "worker.py", line 103, in worker.Worker.run
  File "recorder.py", line 312, in recorder.Recorder.record
  File "jerryrig.py", line 320, in jerryrig.Pipeline.crank
  File "modules/devicereader_module.py", line 100, in modules.devicereader_module.DeviceReaderModule.__call__
  File "modules/devicereader_module.py", line 83, in modules.devicereader_module.DeviceReaderModule.check_reader_status
device.device_error.DeviceError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "core.py", line 86, in core.catch.decorator.wrapper
  File "recorder.py", line 349, in recorder.Recorder.on_record_failed
core.ForgivableError: Reading data from the device failed! Please check the connection to the device and restart the measurement!

[2022-04-22 10:45:02.105] [ 1247 29067] [error] Error: An error occured during recording, <Reading data from the device failed! Please check the connection to the device and restart the measurement!>.
[2022-04-22 10:44:57.508] [ 1247 111378] [debug]  [WingsUsbDevice.cpp            : 571]  NIRSport2 A / 2010_0171_A / 6
[2022-04-22 10:44:57.517] [ 1247 111378] [debug]  [WingsUsbDevice.cpp            : 571]  NIRSport2 B / 2010_0171_B / 6
[2022-04-22 10:47:59.650] [ 1247 29067] [debug] Yes_no question: <There is no selected device. Do you want to open device selection page?>.
[2022-04-22 10:48:04.538] [ 1247 29067] [debug] Yes_no question: <There is no selected device. Do you want to open device selection page?>.
[2022-04-22 10:48:08.883] [ 1247 29067] [debug] Selecting device 2010_0171_A in USB mode
[2022-04-22 10:48:09.018] [ 1247 29067] 
[info] Device configuration: 16x16
[2022-04-22 10:48:09.069] [ 1247 29067] [info] Firmware versions: 0: 1.5.7594.3331, 1: 1.1.7327.3263, 2: 1.1.7327.3263, 3: 1.4.7615.3346, 4: 1.5.7594.3331, 5: 1.5.7594.3331
[2022-04-22 10:48:09.069] [ 1247 29067] [info] Device firmware is up to date
```

Similar errors on lion and tiger. 
[log_leopard.txt](https://github.com/ml4ai/tomcat/files/8543863/log_leopard.txt)
[log_lion.txt](https://github.com/ml4ai/tomcat/files/8543866/log_lion.txt)
[log_tiger.txt](https://github.com/ml4ai/tomcat/files/8543868/log_tiger.txt)

**Comment by CalebUAz** [comment]
@kobus-barnard suggested that on Tuesday's when we do our dry run we stream noise (Aurora didn't crash) and on Friday when we are streaming actual data it crashes. Something to look into?

**Comment by kobus-barnard** [comment]
Further to this: 1) combined with log messages (error reading data) had us thinking that the main difference between the two cases is that people were wearing the caps (perhaps compromising connections) instead of the caps sitting idle collecting noise: 2) it was not clear how many times the exact thing has been done in dry runs, but if it reliable never happens during dry runs, then the explanation is not something that is common to the two cases.

**Comment by adarshp** [comment]
Tomorrow's test will have Minecraft launched *after* Aurora (previously it was launched *before* Aurora) to see if that helps.

@kobus-barnard suggests seeing how many cores Minecraft uses, and if it maxes them out (use the `top` command).

**Comment by adarshp** [comment]
@paulosoaresua reports that Minecraft took 5 CPUs to compile/launch in a test that he ran just now.

**Comment by val-pf** [comment]
04/26
Aurora crashed when starting ffmpeg & minecraft in todays testing session  

Solution for now: **pause fNIRS recording while starting Minecraft.**  
Other possible solutions (to be investigated):
- reduce ffmpeg resolution from 10Hz to 5Hz
- use external box to record & stream screen data (proposed by @rchamplin )

**Comment by adarshp** [comment]
I don't know how we would use an external box to record and stream screen data - it seems fundamentally tied to the iMac.

Other options:
- Buy separate Mac Minis to run Aurora
- Replace iMacs with more powerful macOS or Linux computers (less than ideal...)

**Comment by kobus-barnard** [comment]
Additional compute power via mac minis makes sense. We can do it for about 4x1K$. And we should not spending so much time tuning resource usage. 

However, as we discussed on Monday, we should begin testing running stuff on extra computers (using our laptops or even the spare mac) to get a sense of whether this would help this issue.

**Comment by eduongAZ** [comment]
Testing session on April 26, 2022:
Aurora did not crash when launching Minecraft clients. Aurora priority was still set as default.

However, Aurora did crash after launching ffmpeg to capture screen and webcam.

**Comment by eduongAZ** [comment]
Related to #279
